// Import Metadata type from Next.js for type-safe metadata configuration
import type { Metadata } from "next";
// Import DM_Sans font from Google Fonts
import { DM_Sans } from "next/font/google";
// Import global CSS styles
import "./globals.css";

// Configure DM_Sans font with Latin subset
const dmSans = DM_Sans({
  subsets: ["latin"], // Use only Latin characters subset for better performance
});

// Export metadata for SEO and browser configuration
// This will be used in the document head
export const metadata: Metadata = {
  // Page title displayed in browser tab and search results
  title: "Create Next App",
  // Page description displayed in search engine results
  description: "Generated by create next app",
};

// Root layout component - wraps all pages in the (app) group
// This is the top-level layout that applies to all routes under the (app) folder
export default function RootLayout({
  children,
}: Readonly<{
  // TypeScript type for child components/pages that will be rendered within this layout
  children: React.ReactNode;
}>) {
  return (
    // HTML root element with English language attribute
    <html lang="en">
      {/* Body element with applied font and antialiasing for smooth text rendering */}
      <body
        className={`${dmSans.className} antialiased`}
        // dmSans.className applies the DM_Sans font family to all text
        // antialiased improves font smoothness on screens
      >
        {/* Render child pages/components within the layout */}
        {children}
      </body>
    </html>
  );
}
